# Discord webhook configurations
webhooks:
  discord_manga: "${DISCORD_WEBHOOK_MYANIMELIST}" # MyAnimeList news channel

# Filters for RSS feeds
filters:
  manga_filter: "(?i)(one|bleach|isekai)" # Case-insensitive match for specific anime

# RSS feeds configuration
feeds:
  - name: myanimelist
    url: https://myanimelist.net/rss/news.xml
    webhook: discord_manga
    regex: manga_filter

  - name: crunchyroll
    url: https://cr-news-api-service.prd.crunchyrollsvc.com/v1/en-US/rss
    webhook: discord_manga
    regex: manga_filter
